//
// Created by sakunoakarinn on 22-11-30.
//

#ifndef EXPRESSMANAGEMENTSYSTEM_MENUFORCUSTOMER_H
#define EXPRESSMANAGEMENTSYSTEM_MENUFORCUSTOMER_H


class menuForCustomer {

};


#endif //EXPRESSMANAGEMENTSYSTEM_MENUFORCUSTOMER_H
